### ISSUE TITLE
Problem with ./node_modules/tsx-control-statements/components.ts

### ISSUE THREAD

**Issue by HugoFortunato** [KonstantinSimeonov/tsx-control-statements#218]
## Problem

Basically I get this message when implementing some lib component, for example For .

![image](https://user-images.githubusercontent.com/67443788/172712047-4a2b5f0e-b214-47b4-9084-d504aa2effa3.png)

I'm using nextjs.

I used this for installation in tsx:

`yarn add tsx-control-statements` (https://www.npmjs.com/package/tsx-control-statements)

`yarn add --save-dev babel-plugin-jsx-control-statements`

babel file:

```
{
  "presets": ["next/babel", "@babel/preset-typescript"],
  "plugins": [
    [
      "babel-plugin-styled-components",
      {
        "ssr": true,
        "displayName": true
      }
    ]
  ],
  "env": {
    "test": {
      "plugins": [
        [
          "babel-plugin-styled-components",
          {
            "ssr": false,
            "displayName": false
          }
        ],
        ["jsx-control-statements"],
        ["transform-react-inline-elements"]
      ]
    }
  }
}
```

**Comment by KonstantinSimeonov** [comment]
I'll give it a spin. Sorry for the late response. Weekend is coming up, I'll probs get it sorted out by then

**Comment by KonstantinSimeonov** [comment]
@HugoFortunato Seems like you're trying to mix `jsx-control-statements` and `tsx-control-statements`. I don't think that's meaningful, because:

- if you have a js/ts codebase, `tsx-control-statements` might work for you
- if you have a ts codebase `jsx-control-statements` won't work for you

The way to go with typescript would be to use `ts-patch` to add a transformer to typescript (this might not work because of next babel setup that might use ts for typechecking) or add `ts-loader` with the `tsx-control-statements` transformer. Check out how to do this [here](https://stackoverflow.com/questions/64817528/how-to-use-ts-transformer-keys-in-nextjs-project).

If you have any further trouble, don't hesitate to reach out.
