### ISSUE TITLE
Jest error: Jest encountered an unexpected token

### ISSUE THREAD

**Issue by alexandermckay** [KonstantinSimeonov/tsx-control-statements#4]
Hello,

Does this library work with Jest?

I keep getting the error:

`Jest encountered an unexpected token. This usually means that you are trying to import a file which cannot parse, e.g. it's not plain JavaScript. By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules"`

Everything else works great

Thanks

**Comment by KonstantinSimeonov** [comment]
Hi, thanks for the feedback! I haven't used it with jest (I have very limited experience with jest), but if you're using babel, you should hook the typescript compiler and this library as a custom typescript transformer in webpack config and use that webpack config with jest.

Jest guys have a page on [integrating webpack with jest](https://jestjs.io/docs/en/webpack)
An example of how to hook the typescript compiler with this library as custom transformer in a webpack config can be found [here](https://github.com/KonstantinSimeonov/tsx-control-statements/tree/master/examples/webpack)

I also see that a `ts-jest` thing exists, but I cannot find a way to make it work with the 5 minutes I spent on it. If you need that, I can research it later.

Let me know if that works for you :v:

**Comment by KonstantinSimeonov** [comment]
Some updates:

I've played around with `jest` and `ts-jest` a little bit and I couldn't get it to work. At the end I gave up and jest pre-compiled all the test suites with webpack/typescript and ran the compiled test cases. It's far from ideal, but since `ts-jest` doesn't seem to support custom transformers, that's the best I can do with `jest` at the moment. I'll look into `ts-jest` and see if it would be possible to PR them a custom transformer support implementation.

On the other hand, if using a different test runner would be acceptable in your case, I can recommend `mocha` or `ava`, both of which can use `ts-node`, which supports custom transformers.
